/*! \file
\brief 
Prints pixel values in all or part of an image

\details
  List the pixel values in all or part of an image. In order to reduce
the amount of output, it is usually more useful to print only a small
section of the image by specifying the minimum and maximum pixel in
each dimension to be printed, enclosed in square brackets following
the root file name and optional extension specifier.

Examples: 

-  imlist infile.fit                - print the whole image
-  imlist 'in.fit[*:10,*:10]'       - print every 10th pixel
-  imlist 'in.fit[20:29,10:19]'     - print 10x10 section
-  imlist 'in.fit[20:29:2,10:19:2]' - print every other pixel
-  imlist 'in.fit[3][20:29,10:19]'  - print 3rd IMAGE extension
-  imlist 'intab.fit[1][bin (X,Y)=32] - print image generated by
     binning the X and Y table columns with a binning size = 32

This program opens the file (which may have been filtered) and checks
that the HDU is a 1D or 2D image. It then allocates memory to hold 1
row of pixels, and loops through the image from top to bottom reading
and printing out each row. The data format of the image (integer or
floating point) determines the output display format that is used for
the pixel values. Note that the program reads the image into an array
of doubles, regardless of the intrinsic datatype of the image.

Version 1.0: September 29, 2017 (DP)

Changed format for printing from "%f" to "%e"

  \author Dimitrios Psaltis (updated from 
https://heasarc.gsfc.nasa.gov/docs/software/fitsio/cexamples.html)
  
  \version 1.0
  
  \date September 29, 2017

  \bug No known bugs
  
  \warning no warnings
  
  \todo nothing left

*/
#include <string.h>
#include <stdio.h>
#include "fitsio.h"

int main(int argc, char *argv[])
{
    fitsfile *fptr;   /* FITS file pointer, defined in fitsio.h */
    int status = 0;   /* CFITSIO status value MUST be initialized to zero! */
    int bitpix, naxis, ii, anynul;
    long naxes[2] = {1,1}, fpixel[2] = {1,1};
    double *pixels;
    char format[20], hdformat[20];

    if (argc != 2) {
      printf("Usage:  imlist filename[ext][section filter] \n");
      printf("\n");
      printf("List the the pixel values in a FITS image \n");
      printf("\n");
      printf("Example: \n");
      printf("  imlist image.fits                    - list the whole image\n");
      printf("  imlist image.fits[100:110,400:410]   - list a section\n");
      printf("  imlist table.fits[2][bin (x,y) = 32] - list the pixels in\n");
      printf("         an image constructed from a 2D histogram of X and Y\n");
      printf("         columns in a table with a binning factor = 32\n");
      return(0);
    }

    if (!fits_open_file(&fptr, argv[1], READONLY, &status))
    {
        if (!fits_get_img_param(fptr, 2, &bitpix, &naxis, naxes, &status) )
        {
          if (naxis > 2 || naxis == 0)
             printf("Error: only 1D or 2D images are supported\n");
          else
          {
            /* get memory for 1 row */
            pixels = (double *) malloc(naxes[0] * sizeof(double));

            if (pixels == NULL) {
                printf("Memory allocation error\n");
                return(1);
            }

            if (bitpix > 0) {  /* set the default output format string */
               strcpy(hdformat, " %5d");
               strcpy(format,   " %e");
            } else {
               strcpy(hdformat, " %15d");
               strcpy(format,   " %e");
            }

            printf("\n      ");          /* print column header */
            for (ii = 1; ii <= naxes[0]; ii++)
               printf(hdformat, ii);
            printf("\n");                /* terminate header line */

            /* loop over all the rows in the image, top to bottom */
            for (fpixel[1] = naxes[1]; fpixel[1] >= 1; fpixel[1]--)
            {
               if (fits_read_pix(fptr, TDOUBLE, fpixel, naxes[0], NULL,
                    pixels, NULL, &status) )  /* read row of pixels */
                  break;  /* jump out of loop on error */

               printf(" %4d ",fpixel[1]);  /* print row number */
               for (ii = 0; ii < naxes[0]; ii++)
                  printf(format, pixels[ii]);   /* print each value  */
               printf("\n");                    /* terminate line */
            }
            free(pixels);
          }
        }
        fits_close_file(fptr, &status);
    } 

    if (status) fits_report_error(stderr, status); /* print any error message */
    return(status);
}
